services:
  redis:
    image: redis:latest
    container_name: redis_yagni-server
    ports:
      - '6380:6379'
    volumes:
      - redis-data:/data
      - ../redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  redis-data: